// Code generated by mockery v2.46.3. DO NOT EDIT.

package oauth

import (
	context "context"

	oauth "github.com/rosaekapratama/go-starter/google/cloud/oauth"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// VerifyToken provides a mock function with given fields: ctx, token
func (_m *MockClient) VerifyToken(ctx context.Context, token string) (*oauth.InfotokenResponse, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *oauth.InfotokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*oauth.InfotokenResponse, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *oauth.InfotokenResponse); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauth.InfotokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type MockClient_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockClient_Expecter) VerifyToken(ctx interface{}, token interface{}) *MockClient_VerifyToken_Call {
	return &MockClient_VerifyToken_Call{Call: _e.mock.On("VerifyToken", ctx, token)}
}

func (_c *MockClient_VerifyToken_Call) Run(run func(ctx context.Context, token string)) *MockClient_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_VerifyToken_Call) Return(response *oauth.InfotokenResponse, err error) *MockClient_VerifyToken_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockClient_VerifyToken_Call) RunAndReturn(run func(context.Context, string) (*oauth.InfotokenResponse, error)) *MockClient_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
