filename: "mock_{{.InterfaceName}}.go"
dir: "mocks/{{.InterfaceDirRelative}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
with-expecter: True
packages:
  github.com/rosaekapratama/go-starter/avro:
    interfaces:
      ISchemaManager:
  github.com/rosaekapratama/go-starter/config:
    interfaces:
      Config:
  github.com/rosaekapratama/go-starter/log:
    interfaces:
      Logger:
  github.com/rosaekapratama/go-starter/database:
    interfaces:
      IManager:
  github.com/rosaekapratama/go-starter/google/cloud/oauth:
    interfaces:
      Client:
  github.com/rosaekapratama/go-starter/google/cloud/pubsub/pub:
    interfaces:
      Publisher:
  github.com/rosaekapratama/go-starter/google/cloud/scheduler:
    interfaces:
      IService:
  github.com/rosaekapratama/go-starter/google/cloud/storage:
    interfaces:
      IClient:
  github.com/rosaekapratama/go-starter/redis:
    interfaces:
      ILocker:
      ILock:
  githubcom/rosaekapratama/go-starter/transport/restclient:
    interfaces:
      IManager:
