package sql

const (
	ClauseValues               = " VALUES "
	ClauseWhere                = " WHERE "
	OperatorAnd                = " AND "
	OperatorOr                 = " OR "
	OperatorLike               = " LIKE "
	OperatorIsNull             = " IS NULL "
	OperatorNot                = " NOT "
	OperatorEquals             = " = "
	OperatorNotEquals          = " <> "
	OperatorGreaterThan        = " > "
	OperatorGreaterThanOrEqual = " >= "
	OperatorLessThanOrEqual    = " <= "
	OperatorLessThan           = " < "
	OrderOptAsc                = " ASC "
	OrderOptDesc               = " DESC "
	ConcatFunc                 = " CONCAT "
	TimestampFunc              = " TIMESTAMP "
	LowerFunc                  = " LOWER "
	ToNumberFunc               = " TO_NUMBER "
	StatesTrue                 = " TRUE "
	StatesFalse                = " FALSE "
)
